name: operators_demo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^16.3.3
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
